name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
homepage:
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
 uses-material-design: true
 assets:
  - assets/snowfall.png
  - assets/neoflexlogo.png
  - assets/tree.png
  - assets/snowman.png
  - assets/snow.png
  - assets/gift.png
  - assets/snowflake.png
  - assets/snowflake2.png
  - assets/clouds.png
  - assets/sun.png
  - assets/appletree.png
  - assets/birds.png
  - assets/lilac.png
  - assets/tank.png
  - assets/militarylogo.png
  - assets/star.png
  - assets/moscow.png
  - assets/planes.png

